- pom.xml
> [CLEANUP] Remove duplicate declaration of assembly-plugin

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
> [ENGOPS-2596] added javadoc jar capability

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pentaho-ce-bundle-parent-pom/pom.xml
- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
- pentaho-ce-parent-pom/pom.xml
- pom.xml
@pentaho/2-1b @smaring 
Brought back comments cleared by version merger. Some changes complemented by https://github.com/pentaho/maven-parent-poms-ee/pull/38
@rfellows please make sure i haven't lost any of you license stuff during the merge.
> Backlog 16429

- pom.xml
> [CLEANUP] Adding default filtered resources location

- maven-support-files/settings.xml
- pom.xml
Reverts pentaho/maven-parent-poms#14
> Revert "[BACKLOG-17378] Updating license checking and packaging using the lic…"

- pom.xml
Also cleaned duplicate property.
@pentaho/2-1b @smaring pls review
> [BACKLOG-17829] - updates maven-project-info-reports-plugin version

- pom.xml
@pentaho/2-1b @smaring pls review
> [CLEANUP] - bound install-node-and-npm to a different phase

- pom.xml
> [ENGOPS-3496] prepare for release of CE parent poms to Sonatype

- pom.xml
> [ENGOPS-3496] move sonatype distMgmt to profile

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pentaho-ce-bundle-parent-pom/pom.xml
- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
- pentaho-ce-parent-pom/pom.xml
- pom.xml
> [ENGOPS-1648] added sonatype release failure items

- pom.xml
> [CLEANUP] move eula config prop where version merger can see it

- pom.xml
> [CLEANUP] change license org to Hitachi Vantara

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pentaho-ce-bundle-parent-pom/pom.xml
- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
- pom.xml
> [CLEANUP] Enforce Implementation-Version manifest property to always be present

- maven-support-files/settings.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
> [ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

- pom.xml
@pentaho/2-1b @smaring Please review.
> [BACKLOG-19371] Update maven license helper plugin with pentaho license references

- pom.xml
> [CLEANUP] Adding maven-war-plugin to plugin management

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
> [ENGOPS-1757] version name consolidation

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
> [BACKLOG-21546] added spotbugs rules

- pom.xml
> [ENGOPS-3763] testing nodejs v8.10.0

- pom.xml
> [ENGOPS-2977] Change root dir property setting to be build-helper

- pom.xml
> [BACKLOG-23358] Pentaho Analyzer 7.1 doesn't build

- pom.xml
> Backlog 23247 high

- pom.xml
> Backlog 23247 med

- pom.xml
> [BACKLOG-23945] revert of bundle plugin to 2.5.3

- pom.xml
> [BACKLOG-25739] updated license maven plugin version to 1.27

- pom.xml
This a series of PRs to upgrade `dom4j` from version `1.6.1` to `2.1.1` due to a high risk security vulnerability. **Do not merge until further notice!** See [JIRA](https://jira.pentaho.com/browse/PPP-4182) case for further details.
Full list of PRs (all 29 of them):
- https://github.com/pentaho/maven-parent-poms/pull/70 (this one)
- https://github.com/pentaho/mondrian/pull/1071
- https://github.com/pentaho/pentaho-commons-xul/pull/152
- https://github.com/pentaho/pentaho-connections/pull/26
- https://github.com/pentaho/pentaho-actionsequence-dom/pull/17
- https://github.com/pentaho/pentaho-kettle/pull/5751
- https://github.com/pentaho/pentaho-reportwizard-core/pull/11
- https://github.com/pentaho/pentaho-platform/pull/4230
- https://github.com/pentaho/pentaho-platform-plugin-dashboards/pu …
> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

- pom.xml
> [BACKLOG-22832] Updated reference of pentaho-js-builds version to 2.0.0

- pom.xml
> [PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

- pom.xml
This is a series of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/85
- https://github.com/pentaho/big-data-plugin/pull/1606
- https://github.com/pentaho/data-access/pull/1035
- https://github.com/pentaho/pentaho-platform/pull/4324
> [SP-4828] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

- pom.xml
@graimundo please review. Other PRs will follow after this one is merged.
> [BACKLOG-27564] Centralize Aries Blueprint dependency management

- pom.xml
@graimundo please review. Other PRs will follow after this one is merged.
> [BACKLOG-27568] Centralize pax-url-aether dependency management

- pom.xml
> [BACKLOG-27563] Centralize activemq dependency management

- pom.xml
> [BACKLOG-27569] Centralize pax-web dependency management

- pom.xml
> [BACKLOG-27574] Centralize Felix HTTP dependency version

- pom.xml
> [BACKLOG-27565] Centralize CXF dependency version

- pom.xml
> [BACKLOG-27565] Upgrade CXF to 3.1.9

- pom.xml
> [BACKLOG-27566] Added SLF4J dependency management

- pom.xml
> [PDI-17867] Fixes not closing connections leading to timeouts

- pom.xml
> [ENGOPS-4882] appscan plugin updates

- pom.xml
Centralization of dependencies for CXF, karaf dependencies, karaf-maven-plugin and SLF4J
> [BACKLOG-27511] - Karaf upgrade preparation

- pom.xml
> [PPP-4223] - Spring security vulnerability (CVE-2018-15756)

- pom.xml
> [PPP-4335] Updating com.fasterxml.jackson to 2.9.8

- pom.xml
Reverts pentaho/maven-parent-poms#122
> Revert "[BACKLOG-28357] Updates Apache Derby version"

- pom.xml
Tested this version with pentaho-server locally and all seemed fine, let's hope we get it right this time around
> [BACKLOG-28357] Updates Apache Derby version

- pom.xml
> [PPP-4295] Upgraded activemq version to 5.15.9

- pom.xml
Reverts pentaho/maven-parent-poms#139
@ssamora
> Revert "[PPP-4295] Upgraded activemq version to 5.15.9"

- pom.xml
Removing sonar source configuration.  Each project should define any change or leave the defaults.
depends on https://github.com/pentaho/jenkins-pipelines/pull/271
@pentaho/x-wing pls review
> [BACKLOG-29381] remove sonar source configs

- pom.xml
Reverts pentaho/maven-parent-poms#144
> Revert "[PPP-4295] - Change to the parent pom to use non-vulnerable version o…"

- pom.xml
@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950 
This PR is part of a set of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/151
- https://github.com/pentaho/pentaho-det/pull/1318
- https://github.com/pentaho/pentaho-det-ee/pull/594
> [SP-5148] Backport of PPP-4401 - Use of Vulnerable Component: bootstrap-3.3.6.jar (CVE-2019-8331 | CVE-2018-20677 | CVE-2018-20676) (7.1 Suite)

- pom.xml
This is the first PR of Fancybox upgrade
@pentaho-lmartins @dcleao please review
These are the following PRs:
- https://github.com/pentaho/maven-parent-poms/pull/157
- https://github.com/webdetails/cdf/pull/1092
- https://github.com/webdetails/cde/pull/946
> [PPP-4008] - Fancybox upgrade to 3.5.5

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
- pom.xml
> [CLEANUP] Review sonar configuration

- pom.xml
----
----
----
----
----
----
----
> [BACKLOG-27590] Upgrade to Karaf 4.2.6

- pom.xml
**Attention: This is the outcome of an automated process!**
Merge Masters: @pentaho-lmartins and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/maven-parent-poms/commit/9d0c365a58f6e11a10dc8a0103dcc16dce3d3974
> [SP-5323] Backport of PPP-4447 - Use of vulnerable component - Tika Core 1.1x (8.3 Suite)

- pom.xml
> [BACKLOG-32987] Updating copyrights to 2020

- maven-support-files/settings.xml
- pom.xml
> [BACKLOG-32935] artifactory updates

- pom.xml
@pentaho/millenniumfalcon please review.
> [BACKLOG-33070] Upgrade jQuery to fix IE11 bug.

- pom.xml
> [ENGOPS-6587] update version of appscan maven plugin

- pom.xml
@pentaho/millenniumfalcon please review.
> [BACKLOG-33393] Add angular.version property to parent pom.

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
(cherry picked from commit 4337530b49f923d8a39ede77fbf80e7bc10bb207)
> [CLEANUP] add custom CI surefire/failsafe argLine configuration.

- pom.xml
@pentaho/millenniumfalcon 
/cc: @pentaho/r2d2 
Dependent PRs:
- https://github.com/pentaho/pentaho-osgi-bundles/pull/361
- https://github.com/pentaho/pentaho-platform/pull/4650
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1502
- https://github.com/pentaho/marketplace/pull/180
- https://github.com/pentaho/pentaho-analyzer/pull/2076
- https://github.com/pentaho/pentaho-det/pull/1337
- https://github.com/pentaho/pentaho-det-ee/pull/614
- https://github.com/pentaho/pentaho-kettle/pull/7311
- https://github.com/pentaho/pdi-plugins-ee/pull/169
- https://github.com/pentaho/big-data-plugin/pull/2033
> [PPP-4413] Use of vulnerable component - Angular.js v1.5.8

- pom.xml
@bcostahitachivantara @smmribeiro @pentaho-lmartins
> [BACKLOG-34973] Copyright data (year) not updated after applying SP

- pom.xml
> [PDI-18729] Update commons-vfs library to pull in fixes for sftp thread

- pom.xml
@bcostahitachivantara @smmribeiro 
Other PR's for this correction:
https://github.com/pentaho/pentaho-osgi-bundles/pull/379
https://github.com/pentaho/pentaho-platform/pull/4816
https://github.com/pentaho/pentaho-platform-ee/pull/1434
> [PPP-4546] Use of Vulnerable Component: Components/jquery:3.4.1

- pom.xml
> [BACKLOG-35047] Update Spring libraries to latest versions to address

- pom.xml
Reverts pentaho/maven-parent-poms#264
> Revert "[BACKLOG-35047] Update Spring libraries to latest versions to address"

- pom.xml
Please, review:
@graimundo
/cc @bennychow if you want to review, be my guest!
/cc @jcarneirohv
Part of a group of PRs headed by pentaho/security-web#4.
> [BACKLOG-35000] Adding _HV Security Web library_ version and dependency management info

- pom.xml
> [PPP-4686] Update Tomcat version to 9.0.50 to mitigate CVE-2021-30639

- pom.xml
…cy management info (#280)
I have no permissions to push directly to a feature branch of this repo, to be able rebase it, so here we go the PR way...
> [BACKLOG-35000] Rebase branch

- pom.xml
Had to rebase into master which, because I didn't have permission to force push, required someone from engops to delete the remote branch, me to recreate it based on master and opening this PR from my rebased branch...
> [BACKLOG-35000] Adding _HV Security Web library_ version and dependency management info (#280)

- pom.xml
(cherry picked from commit 05b93ea149af7adf702eed8662089e68c9d1f51d)
> [SP-5972][PPP-4655] Upgrade xstream to 1.4.17

- pom.xml
(cherry picked from commit 05b93ea149af7adf702eed8662089e68c9d1f51d)
> [SP-5973][PPP-4655] Upgrade xstream to 1.4.17

- pom.xml
- Dependency has changed parent pom, which affects downstream access to artifacts.
@smaring please review and merge
> [BACKLOG-35001] Upgrade security-web dependency

- pom.xml
@bennychow, @ddiroma please review.
Depends on: https://github.com/pentaho/security-web/pull/11
> [BACKLOG-35298] Upgrade security-web dependency

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PDI-19324] - Upgrade Snowflake JDBC Driver

- pom.xml
@bennychow please review and merge.
/cc @spravasahu, @sVarma1992
NOTE: this is merging to the CSRF feature branch ([BACKLOG-35000](https://github.com/pentaho/maven-parent-poms/tree/BACKLOG-35000)).
To merge _after_ the following: https://github.com/pentaho/security-web/pull/13
Please do not squash commits.
> [BACKLOG-30667] Update version of HV security-web and add new available security web artifact

- pom.xml
@smaring @pminutillo please review
> [PPP-4481] - Upgrade h2 library

- pom.xml
> [BACKLOG-35509] Keep paramters referenced in ant scripts, build with

- pom.xml
Reverts pentaho/maven-parent-poms#334
> Revert "[BACKLOG-35886] Upgrade Maven jar plugin"

- pom.xml
[PPP-4654] added apache commons-io non-vulnerable version
> [PPP-4654] added apache commons-io non-vulnerable version

- pom.xml
This commit is a cherry-pick from master d5b97bce
> [SP-6179] [PPP-4654] added apache commons-io non-vulnerable version

- pom.xml
Reverts pentaho/maven-parent-poms#351
> Revert "[PPP-4705] update tomcat version"

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-4755] - Vulnerable Component: Spring 5.3.3

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-4758] - Vulnerable Component: Spring Security - CVE-2022-22978

- pom.xml
Reverts pentaho/maven-parent-poms#357
> Revert "[PPP-4758] - Vulnerable Component: Spring Security - CVE-2022-22978"

- pom.xml
@renato-s 
@smmribeiro 
@bcostahitachivantara
> [SP-6229] - Backport of PPP-4755 - Vulnerable Component: Spring 5.3.3(9.3 Suite)

- pom.xml
> [PPP-4812] -CVE-2022-42252 : Tomcat Request Smuggling Vulnerability.

- pom.xml
> [PPP-4812] - CVE-2022-42252 : Tomcat Request Smuggling Vulnerability.

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-4754] - Use of outdated JavaScript libraries

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-4752] - Vulnerable Component: PostgreSQL JDBC Driver 42.2.23

- pom.xml
Reverts pentaho/maven-parent-poms#356
> Revert "[PPP-4704] - Vulnerable Component: xstream-1.4.17"

- pom.xml
@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/371
> [SP-6281] - Backport of PPP-4812 - CVE-2022-42252 : Tomcat Request Smuggling Vulnerability. (9.4 Suite)

- pom.xml
@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/371
> [SP-6280] - Backport of PPP-4812 - CVE-2022-42252 : Tomcat Request Smuggling Vulnerability. (9.3 Suite)

- pom.xml
> [SP-6264] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.3 Suite)

- pom.xml
> [SP-6265] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.4 Suite)

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-4827] - Vulnerable Component: Spring Security - CVE-2022-31692

- pom.xml
> [SP-6230] - Backport of PPP-4755 - Vulnerable Component: Spring 5.3.3 (9.4 Suite)

- pom.xml
> [PPP-4704] - Vulnerable Component: xstream-1.4.17

- pom.xml
> [SP-6250] -Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.3 Suite)

- pom.xml
> [SP-6251] - Backport of PPP-4704 - Vulnerable Component: xstream-1.4.17 (9.4 Suite)

- pom.xml
> [PPP-4828] - Component Rome is outdated

- pom.xml
@smmribeiro 
@andreramos89 
@renato-s
> [PPP-3713] - Beanshell version we're using is vulnerable to serialization exploit - CVE-2016-2510

- pom.xml
support license manager changes.
> [BACKLOG-37368] Update bouncycastle dependency to latest version to

- pom.xml
Reverts pentaho/maven-parent-poms#406
> Revert "[BACKLOG-37531] Bouncycastle release/version mismatch causing problems"

- pom.xml
> [PPP-4802] -  Vulnerable Component: hsqldb

- pom.xml
@bcostahitachivantara @renato-s @andreramos89
> [PPP-4868] Vulnerable Component: Apache Tomcat (CVE-2023-28708)

- pom.xml
Reverts pentaho/maven-parent-poms#413
@jmcrfp 
@bcostahitachivantara @renato-s @andreramos89
> Revert "[PPP-4868] Vulnerable Component: Apache Tomcat (CVE-2023-28708)"

- pom.xml
This reverts commit 48bdd7d738fb244d4e832c28df97de507a53a9eb.
> Revert "[PDI-18433] Upgrade commons-vfs2 to 2.9.0"

- pom.xml
(cherry picked from commit 911778d78ab6ce5ba3335f9ce7c6982683253f18)
> [BACKLOG-36830] - Kafka Enhancements (Plug-in Release)

- pom.xml
> [PPP-4879] - Vulnerable Component: Spring 5.3.23

- pom.xml
@andreramos89 
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/436
> [SP-6376] - Backport of PPP-4879 - Vulnerable Component: Spring 5.3.23 (9.3 Suite)

- pom.xml
@andreramos89 
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/436
> [SP-6373] - Backport of PPP-4879 - Vulnerable Component: Spring 5.3.23 (9.5 Suite)

- pom.xml
Original PR: [https://github.com/pentaho/maven-parent-poms/pull/437](https://github.com/pentaho/maven-parent-poms/pull/437)
@renato-s 
@smmribeiro 
@bcostahitachivantara
> [SP-6383] - Backport of PPP-4882 -  Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3 (9.3 Suite)

- pom.xml
Original PR: [https://github.com/pentaho/maven-parent-poms/pull/437](https://github.com/pentaho/maven-parent-poms/pull/437)
@renato-s 
@smmribeiro
> [SP-6384] - Backport of PPP-4882 - Vulnerable Component: Spring Security - (CVE-2023-20861) after applying 9.3.0.3 (9.5 Suite)

- pom.xml
Reverts pentaho/maven-parent-poms#448
> Revert "[PPP-4921] Vulnerable Component: Jackrabbit"

- pom.xml
@bcostahitachivantara @renato-s @andreramos89
> [PPP-4946] Vulnerable Component: Tomcat

- pom.xml
Original pull requests: https://github.com/pentaho/maven-parent-poms/pull/417 and https://github.com/pentaho/maven-parent-poms/pull/445
@smmribeiro 
@renato-s
> [SP-6416] - Backport of PPP-4829 - Upgrade Rhino on PRD and PDI (9.3 Suite)

- pom.xml
Updating Spring Security version to 5.8.7
@smmribeiro 
@renato-s 
@bcostahitachivantara
> [PPP-4872] - Vulnerable Component: Spring Security

- pom.xml
[PPP-4747] Vulnerable Component: batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4747] Vulnerable Component: batik-1.19

- pom.xml
@bcostahitachivantara @renato-s @andreramos89 
(please don't merge this until [DEVO-9149](https://hv-eng.atlassian.net/browse/DEVO-9149) is finished)
[DEVO-9149]: https://hv-eng.atlassian.net/browse/DEVO-9149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4965] Vulnerable Component: Tomcat (again)

- pom.xml
[PPP-4949] Vulnerable Component: Xerces
[PPP-4949]: https://hv-eng.atlassian.net/browse/PPP-4949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4949] Vulnerable Component: Xerces

- pom.xml
Reverts pentaho/maven-parent-poms#465
> Revert "[PDI-19906] - Google BigQuery Simba driver version 1.3.3.1004 in Pentaho"

- pom.xml
[PPP-4747] -Vulnerable Component :batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4747] -Vulnerable Component :batik-1.19

- pom.xml
[PPP-4747]-Vulnerable Component :batik:1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4747]-Vulnerable Component :batik:1.19

- pom.xml
[PPP-4782]-Vulnerable Component:Jackson Libraries
[PPP-4782]: https://hv-eng.atlassian.net/browse/PPP-4782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4782]-Vulnerable Component:Jackson Libraries

- pom.xml
[PPP-4936]-Vulnerable Component -Guava upgraded to 32.1.2-jre version
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4936]-Vulnerable Component -Guava upgraded to 32.1.2-jre version

- pom.xml
[PPP-4782] -Vulnerable Component:Jackson Libraries
[PPP-4782]: https://hv-eng.atlassian.net/browse/PPP-4782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4782] -Vulnerable Component:Jackson Libraries

- pom.xml
> [PPP-4751] - Vulnerable Component: org.apache.activemq:activemq-all:5.10.1 - fixing vulnerable component issue

- pom.xml
@smmribeiro 
@renato-s 
@bcostahitachivantara
> [SP-6440] - Backport of PPP-4751 - Vulnerable Component: org.apache.activemq:activemq-all:5.10.1 - fixing vulnerable component issue

- pom.xml
[PPP-4891]-Vulnerable Component :Commons-beanutils
[PPP-4891]: https://hv-eng.atlassian.net/browse/PPP-4891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4891]-Vulnerable Component :Commons-beanutils

- pom.xml
Upgrading to 9.0.84
@renato-s @andreramos89
> [PPP-5033] Vulnerable Component: Tomcat 9.0.82

- pom.xml
[PPP-4833] :Vulnerable Component :h2
[PPP-4833]: https://hv-eng.atlassian.net/browse/PPP-4833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4833] :Vulnerable Component :h2

- pom.xml
@pentaho/millenniumfalcon @smaring @cardosov please review
Depends on:
- https://github.com/pentaho/jenkins-pipelines/pull/938
- https://github.com/pentaho/jenkins-pipelines/pull/939
> chore: move headless sandbox profile to parent poms [BACKLOG-40011]

- pom.xml
Upgrading Tomcat to 9.0.86
@renato-s @andreramos89
> [PPP-5067] Vulnerable Component: Tomcat 9.0.84

- pom.xml
For this PR to work, we need to add to the repo, the forked versions of jackson-dataformat-yaml and safeyaml
@renato-s 
@smmribeiro
> [PPP-4865] - Vulnerable Component: snakeyaml - replace Snakeyaml with Safeyaml

- pom.xml
> [PPP-5069] Vulnerable Component: Spring

- pom.xml
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/538
> [SP-6530] - Backport of PPP-5070 - Vulnerable Component: PostgreSQL JDBC (10.1 Suite)

- pom.xml
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/538
> [SP-6529] - Backport of PPP-5070 - Vulnerable Component: PostgreSQL JDBC (9.3 Suite)

- pom.xml
Original PR: [maven-parent-poms#531](https://github.com/pentaho/maven-parent-poms/pull/531)
@renato-s @andreramos89 @befc @joana-fb @miguelappleton
> [SP-6516] Backport of PPP-5067 - Vulnerable Component: Tomcat 9.0.84 (9.3 Suite)

- pom.xml
Original PR: [maven-parent-poms#531](https://github.com/pentaho/maven-parent-poms/pull/531)
@renato-s @andreramos89 @befc @joana-fb @miguelappleton
> [SP-6517] Backport of PPP-5067 - Vulnerable Component: Tomcat 9.0.84 (10.1 Suite)

- pom.xml
Original PR: [maven-parent-poms#548](https://github.com/pentaho/maven-parent-poms/pull/548)
> [SP-6548] Backport of PPP-5069 - Vulnerable Component: Spring (9.3 Suite)

- pom.xml
Original PR: [maven-parent-poms#548](https://github.com/pentaho/maven-parent-poms/pull/548)
> [SP-6549] Backport of PPP-5069 - Vulnerable Component: Spring (10.1 Suite)

- pom.xml
[PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

- pom.xml
> [PPP-5122] Vulnerable Component: Tomcat

- pom.xml
[PPP-5083]-Vulnerable Component: ion java
[PPP-5083]: https://hv-eng.atlassian.net/browse/PPP-5083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-5083]-Vulnerable Component: ion java

- pom.xml
[PPP-5077]-Vulnerable Component: mina-core
[PPP-5077]: https://hv-eng.atlassian.net/browse/PPP-5077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PPP-5077]-Vulnerable Component: mina-core

- pom.xml
[REVERT] PPP-5077-Vulnerable Component: mina-core
> [REVERT] PPP-5077-Vulnerable Component: mina-core

- pom.xml
@pentaho/millenniumfalcon @pentaho/sp-branch-write please review
Related PRs:
- https://github.com/pentaho/big-data-plugin/pull/2613
- https://github.com/pentaho/pentaho-kettle/pull/9567
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1788
> chore: centralize dojo.version [PPP-4824]

- pom.xml
[SP-6584]-Backport of PPP-5004 - Tomcat Configuration vulnerable to Server-Side Request Forgery (9.3 Suite)
[SP-6584]: https://hv-eng.atlassian.net/browse/SP-6584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6584]-Backport of PPP-5004 - Tomcat Configuration vulnerable to Server-Side Request Forgery (9.3 Suite)

- pom.xml
Original PR:
- https://github.com/pentaho/maven-parent-poms/pull/603
Related PRs:
- https://github.com/pentaho/pentaho-kettle/pull/9588
- https://github.com/pentaho/big-data-plugin/pull/2621
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1790
- https://github.com/pentaho/pentaho-analyzer/pull/2647
The PRs above need this PR merged, in order for wingman builds to be successful
> [SP-6590] Backport of PPP-4824 - Vulnerable Component: dojo 1.9.3 (10.2 Suite)

- pom.xml
[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

- pom.xml
Do not merge into master yet. This is marked for 10.4 or 10.2.0.2 release.
Linked PR https://github.com/pentaho/pdi-plugins-ee/pull/1413
> [PPP-4979] - Vulnerable Component: amqp-client

- pom.xml
[BACKLOG-41287]-Upgrading libraries to be compatiable with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41287]-Upgrading libraries to be compatiable with Tomcat-10.X

- pom.xml
[BACKLOG-41287]-Upgrading libraries to be compatible with Tomcat-10.X
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41287]-Upgrading libraries to be compatible with Tomcat-10.X

- pom.xml
[SP-6687]-Backport of PPP-5366 - Vulnerable Component: Spring Security 5.8.12 (10.2 Suite)
[SP-6687]: https://hv-eng.atlassian.net/browse/SP-6687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6687]-Backport of PPP-5366 - Vulnerable Component: Spring Security 5.8.12 (10.2 Suite)

- pom.xml
Reverts pentaho/maven-parent-poms#646
> Revert "Karaf upgrade 4.4.6 10.2"

- pom.xml
[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

- pom.xml
> [PPP-5447] - Vulnerable Component: XStream 1.4.20

- pom.xml
[BACKLOG-43209]-OSGI Assembly issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43209]-OSGI Assembly issues

- pom.xml
[BACKLOG-41287]-Upgrading Hibernate dependent jars
[BACKLOG-41287]: https://hv-eng.atlassian.net/browse/BACKLOG-41287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41287]-Upgrading Hibernate dependent jars

- pom.xml
- Update pax-url-aether version: 2.6.14 -> 2.6.16
> [PPP-5589] [PPP-5618] Vulnerable Component: commons-io (Karaf)

- pom.xml
> feat: bump tomcat to 9.0.100 [PPP-5627]

- pom.xml
Added comments to ensure that when updating tomcat, pax-web is also updated.
> feat: bump pax-web to 8.0.31 [PPP-5627]

- pom.xml
@pentaho/tatooine_dev 
Related PRs:
https://github.com/webdetails/cdf/pull/1192
https://github.com/webdetails/cde/pull/1046
https://github.com/webdetails/sparkl/pull/95
https://github.com/pentaho/pentaho-platform/pull/5863
https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1831
> chore: upgrade underscore version [PPP-5515]

- pom.xml
Reverts pentaho/maven-parent-poms#682
> Revert "chore: upgrade underscore version [PPP-5515]"

- pom.xml
Reverts pentaho/maven-parent-poms#681
> Revert "feat: bump pax-web to 8.0.31 [PPP-5627]"

- pom.xml
Reverts pentaho/maven-parent-poms#685
> Revert "feat: bump tomcat to 9.0.100 [SP-6788]"

- pom.xml
Related PRs:
- https://github.com/pentaho/maven-parent-poms-ee/pull/102
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1835
- https://github.com/pentaho/pentaho-analyzer/pull/2697
- https://github.com/pentaho/pentaho-platform-plugin-geo/pull/424
- https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/600
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/892
- https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/1134
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/319
- https://github.com/pentaho/pentaho-reportdesigner-ee/pull/296
- https://github.com/pentaho/pentaho-det/pull/1390
- https://github.com/pentaho/pentaho-det-ee/pull/699
- …
> fix: vulnerable component requirejs [PPP-5516]

- pom.xml
Original PRs:
- https://github.com/pentaho/maven-parent-poms/pull/667
- https://github.com/pentaho/maven-parent-poms/pull/680
- https://github.com/pentaho/maven-parent-poms/pull/692
> [SP-6788] Backport of PPP-5627 - Vulnerable Component: Tomcat 9.0.98 (10.2 Suite)

- pom.xml
> [SP-6820] Backport of PPP-5116 - Vulnerable Component: JQuery UI (10.2 Suite)

- pom.xml
> chore: Upgrade Spring Security to 5.8.16 and Spring LDAP to 2.4.4 [PPP-5481]

- pom.xml
To be merged with:
- https://github.com/webdetails/cdf/pull/1201
- https://github.com/webdetails/cde/pull/1051
- https://github.com/webdetails/sparkl/pull/98
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1844
- https://github.com/pentaho/pentaho-platform/pull/5885
- https://github.com/pentaho/pentaho-osgi-bundles/pull/528
- https://github.com/pentaho/pentaho-det/pull/1393
Original PR: https://github.com/pentaho/maven-parent-poms/pull/695
Issues: https://hv-eng.atlassian.net/browse/PPP-5515 and https://hv-eng.atlassian.net/browse/SP-6838
> [SP-6838] Backport of PPP-5515 - Vulnerable Component: underscore 1.8.3 (10.2 Suite)

- pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

- pom.xml
[BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
[BACKLOG-43935]: https://hv-eng.atlassian.net/browse/BACKLOG-43935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures

- pom.xml
This reverts commit 09471376a855849362c103721f0a9b63b2abd48f.
> Revert "[BACKLOG-41964] OAuth changes"

- pom.xml
> feat: bump vfs2 to 2.10.0 [PPP-5649]

- pom.xml
> feat[PPP-5649]: add/fix optional dependencies

- pom.xml
Original PRs:
1. https://github.com/pentaho/maven-parent-poms/pull/728
2. https://github.com/pentaho/maven-parent-poms/pull/729
> feat[SP-6856]: add/fix optional dependencies

- pom.xml
@pentaho/tatooine_dev please review
> build[SP-6872]: Bump commons-beanutils version to 1.11.0

- pom.xml
> feat[PPP-5765]: bump tomcat to 9.0.107

- pom.xml
> chore[PPP-5719]: upgrade Saxon dependency

- pom.xml
Reverts pentaho/maven-parent-poms#744
> Revert "chore[PPP-5719]: upgrade Saxon dependency"

- pom.xml
Reverts pentaho/maven-parent-poms#750
> Revert "chore[PPP-5719]: move xmlresolver, json-simple and xmlunit to parent pom"

- pom.xml
> build[PPP-5769] fix Karaf versioning

- pom.xml
[BACKLOG-45196]-When XML file with null values are read, there is closing tags being added to that field, that is causing our tests to fail
[BACKLOG-45196]: https://hv-eng.atlassian.net/browse/BACKLOG-45196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-45196]-When XML file with null values are read, there is closing tags being added to that field, that is causing our tests to fail

- pom.xml
> chore[PPP-5719]:  move xmlresolver, json-simple and xmlunit to parent pom

- pom.xml
[BACKLOG-45760]-The LDAP setup is failing
[BACKLOG-45760]: https://hv-eng.atlassian.net/browse/BACKLOG-45760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-45760]-The LDAP setup is failing

- pom.xml
> fix[SP-6900]: fix common-fileupload version

- pom.xml
> feat: bump maven compiler version [BACKLOG-45596]
