pentaho/maven-parent-poms

- pom.xml
This fixes a few issues that we have run into recently
* an issue with open filehandles on some laptops ( @tmcsantos )
* an issue generating zip files that are not compatible with the pentaho platform importer ( i found this while converting pentaho-platform-ee to maven)
> [CLEANUP] - upgrading to maven-assembly-plugin 3.0.0.

- pom.xml
I would prefer to have a property called "mindtouch" to control the switching but then we would need to negate the property value to disable private docs (mindtouch = true => jsdoc.config.opts.private = false), and this functionality isn't available in maven.
> [BACKLOG-14318] Extra configuration for jsdoc to check if we are doing a local build

- pom.xml
This is filling up generic private-release and public-release with artifcats that don’t belong there.
> [CLEANUP] No more default deploy repo URLs

- pom.xml
@pentaho/x-wing @graimundo Please review
Can be bypassed by using a `skipNodeClean` property.
> [BACKLOG-16958] Adds removal of node_modules dir to maven clean

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
- pom.xml
- Adds code-audit profile.
- Moves checkestyle to code-audit and bind it to validate phase.
- Moves jacoco reports to code-audit.
depends on:
https://github.com/pentaho/pentaho-wingman/pull/90
> [BACKLOG-19308] - audit profile 

- pom.xml
The property was misspelled, but had an incorrect version, should be 3.0.8 until we update karaf to 4
> [CLEANUP] missing karaf-maven-plugin property

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pentaho-ce-bundle-parent-pom/pom.xml
- pom.xml
Merge the rest, only after this one and https://github.com/pentaho/maven-parent-poms-ee/pull/68:
- https://github.com/pentaho/build-utils-js/pull/4
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1345
- https://github.com/pentaho/pentaho-analyzer/pull/1879
- https://github.com/pentaho/pentaho-platform-plugin-geo/pull/278
- https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/725
- https://github.com/pentaho/pentaho-osgi-bundles/pull/292
- https://github.com/pentaho/pentaho-kettle/pull/6009
- https://github.com/pentaho/pentaho-det/pull/1279
- https://github.com/pentaho/pentaho-det-ee/pull/574
- https://github.com/webdetails/ccc/pull/353
- https://github.com/webdetails/cdf/pull/1050
- https://github.com/webdetails/cde/pull/915 …
> [BACKLOG-22832] Upgrade require.js and r.js to version 2.3.6

- pom.xml
* [PPP-4266] Added in the version for commons-fileupload and created the dependency reference. Any relevant projects that utilize the commons-fileupload will be updated to reference this (if we need to update the version again, we just update this file)
This is a series of PRs:
- #83 
- pentaho/big-data-plugin#1599
- pentaho/data-access#1033
- pentaho/pentaho-platform#4311
> [PPP-4266] Use of Vulnerable Component commons-fileupload CVE-2016-1000031

- pom.xml
This is a series of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/86
- https://github.com/pentaho/big-data-plugin/pull/1607
- https://github.com/pentaho/data-access/pull/1036
-
> [SP-4827] - Backport of PPP-4266 - Use of Vulnerable Component: commons-fileupload-1.3.2.jar (CVE-2016-1000031 | sonatype-2014-01730) (7.1 Suite)

- pom.xml
@graimundo please review. Others will follow cleaning up overrides to 5.0.0 no longer needed.
> [BACKLOG-27567] Use org.osgi.* 5.0.0

- pom.xml
This is a series of PRs to update the version of AWS Java SDK across all repositories.
1. https://github.com/pentaho/maven-parent-poms/pull/112 (added version only)
2. https://github.com/pentaho/pentaho-s3-vfs/pull/50
3. https://github.com/pentaho/pentaho-kettle/pull/6323
4. https://github.com/pentaho/big-data-plugin/pull/1641
5. https://github.com/pentaho/pentaho-ee/pull/1914
@pentaho/tatooine @ssamora
> [PDI-17867] Fixes not closing connections leading to timeouts

- pom.xml
Removal of the Apache Derby version in favor of retrieving a unified version from the Maven parent POM. At the time of this PR, the latest version of Apache Derby is 10.15.1.3.
> [BACKLOG-28357] Updates Apache Derby version

- pom.xml
Reverts pentaho/maven-parent-poms#134
> Revert "[PDI-17794] Warnings in Spoon console due to wrong version of log4j"

- pom.xml
Reverts pentaho/maven-parent-poms#136
@ssamora
> Revert "[PPP-4295] - Change to the parent pom to use non-vulnerable version o…"

- pom.xml
@pentaho/tatooine @wseyler @pentaho-lmartins 
* [PPP-4401] Added bootstrap reference to maven parent pom project. Updated version number per PPP-4401 ticket reference
This Pull Request is a part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/146
- https://github.com/pentaho/pentaho-det/pull/1308
- https://github.com/pentaho/pentaho-det-ee/pull/590
> [PPP-4401] Use of Vulnerable Component: bootstrap-3.3.6.jar (CVE-2019-8331 | CVE-2018-20677 | CVE-2018-20676)

- pom.xml
@pentaho/tatooine  @pentaho-lmartins @wseyler
* [PPP-4400] Moving dependency reference and version info to the maven-parent-pom repo
This Pull Request is part of a series of Pull Requests:
- https://github.com/pentaho/maven-parent-poms/pull/145
- https://github.com/pentaho/pdi-osgi-bridge/pull/73
- https://github.com/pentaho/pdi-monitoring-plugin/pull/96
- https://github.com/pentaho/pentaho-ee/pull/2128
- https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/227
- https://github.com/pentaho/pentaho-osgi-bundles/pull/324
> [PPP-4400] Use of Vulnerable Component: logback-classic-1.1.11.jar (CVE-2017-5929)

- pom.xml
@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950 
This PR is part of a set of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/152
- https://github.com/pentaho/pentaho-det/pull/1320
- https://github.com/pentaho/pentaho-det-ee/pull/595
> [SP-5149] Backport of PPP-4401 - Use of Vulnerable Component: bootstrap-3.3.6.jar (CVE-2019-8331 | CVE-2018-20677 | CVE-2018-20676) (8.3 Suite)

- pom.xml
@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950
This PR is a part of a set of PRs (pentaho-ee was not backported as the relevant file was added in version 8.0+):
- https://github.com/pentaho/maven-parent-poms/pull/150
- https://github.com/pentaho/pdi-osgi-bridge/pull/77
- https://github.com/pentaho/pdi-monitoring-plugin/pull/98
- https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/229
- https://github.com/pentaho/pentaho-osgi-bundles/pull/326
> [SP-5146] Backport of PPP-4400 - Use of Vulnerable Component: logback-classic-1.1.11.jar (CVE-2017-5929) (7.1 Suite)

- pom.xml
@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950 
This PR is a part of a set of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/149
- https://github.com/pentaho/pdi-osgi-bridge/pull/76
- https://github.com/pentaho/pdi-monitoring-plugin/pull/97
- https://github.com/pentaho/adaptive-execution-layer/pull/5
- https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/228
- https://github.com/pentaho/pentaho-osgi-bundles/pull/325
> [SP-5147] Backport of PPP-4400 - Use of Vulnerable Component: logback-classic-1.1.11.jar (CVE-2017-5929) (8.3 Suite)

- pom.xml
Replaces #172. This is a series of PRs:
- https://github.com/pentaho/maven-parent-poms/pull/178 (this one)
- https://github.com/pentaho/pentaho-platform/pull/4580
- https://github.com/pentaho/pentaho-kettle/pull/7016
- https://github.com/pentaho/data-access/pull/1076
Updates `jackrabbit-*` to version 2.16.5 and `tika-core` to version 1.22.
@ssamora @RPAraujo
> [PPP-4447] Use of vulnerable component - Tika Core 1.1x

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pentaho-ce-bundle-parent-pom/pom.xml
- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
- pom.xml
This will update `build-helper-maven-plugin` to our custom build which fixes the `rootlocation` goal.
> [BACKLOG-30710] - update build-helper-maven-plugin

- pom.xml
@pentaho/millenniumfalcon please review.
> [BACKLOG-33070] Add warning message near `jquery.version` property.

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pom.xml
@pentaho/x-wing Wingman needs to set extra JVM args for forked surefire/failsafe executions, but the way it implemented is overriding any project's custom arguments. 
This adds a dedicated CI place to add configurations without overriding the project ones.
> [CLEANUP] add custom CI surefire/failsafe argLine configuration.

- pom.xml
Bumping tomcat version to 8.5.51 to address CVE-2020-1938.
@ssamora
> [PPP-4506] Use of Vulnerable component - Tomcat 8.5.50 - CVE-2020-1938

- pom.xml
This reverts commit dd998a842948fa7b27ab91c324417065baa5d690, reversing
changes made to 7311a5827e06a2002395bbabd78a9ab8a10b2418.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …
> Revert "Merge pull request #220 from gryphendowre/SP-5370"

- pom.xml
Although I'm not a fan of using ant from maven in this case I found it troublesome to use a combination of the assembly plugin for zipping and build-helper to attach the artifact.
AFAIK the assembly plugin does not allow having the assembly descriptor to be inline in the POM. It requires the assembly descriptors to be defined externally in a dedicated file(s). This external descriptor would not seamlessly "pass along" to the descendant POMs where the profile will be activated.
With the maven antrun plugin we are able to achieve the goal with a clean and simple solution. 
Let me know if there is a better alternative.
> [BACKLOG-33815] - Added profile to create and attach artifact with proto specification files.

- pom.xml
@pentaho/millenniumfalcon, @pentaho/r2d2 please review.
Merge along with: https://github.com/pentaho/pentaho-osgi-bundles/pull/373.
> [BACKLOG-34196] Upgrade Angular JS library from 1.7.8 version to 1.8.0

- pom.xml
Adding endorsed standards excluded from java 11 in preparation for java 11 changes to other repos.
> [BACKLOG-35251] Java 11 compatibility

- pom.xml
Gwt and gwtx versions still need to be changed; will do this in another PR.
> [BACKLOG-35286] Gwt Java 11 compatibility change preparations. 

- pom.xml
> [BACKLOG-35287] New version of simple-jndi compatible with both jdk 8

- pom.xml
- Dependency has added support for the CSRF token parameter to be specified in the body, as part of, e.g. a POST request
Depends on https://github.com/pentaho/security-web/pull/10.
@bennychow, @ddiroma please review and merge.
> [BACKLOG-35298] Upgrade security-web dependency

- pom.xml
8.  Use javac -release option to build for Java 8 compatibility and link
to correct platform libraries.
> [BACKLOG-35509] Fix for NoSuchMethodError running CSV Input step on Java

- pom.xml
The essential part for everything to work, is the addition of "/Pentaho" to the URL, because "help.pentaho.com" redirects to "help.hitachivantara.com".
The change "pentaho->hitachivantara" is normally done when the "code is touched" - and it translates into one less redirect :-)
@bcostahitachivantara @renato-s @andreramos89
@rmansoor @smaring
> [PDI-19520] PDI Welcome screen has wrong links

- pom.xml
Depends on https://github.com/pentaho/security-web/pull/19.
PR set:
- https://github.com/pentaho/pentaho-platform/pull/5104
- https://github.com/pentaho/pentaho-platform-ee/pull/1532
> [BACKLOG-35980] Change security-web version to 0.11.0

- pom.xml
- version 0.8.2+ fully supports java 11.
> [BACKLOG-36442] upgrade jacoco-maven-plugin:0.8.1 -> 0.8.8

- pom.xml
Reverts pentaho/maven-parent-poms#361
Inadvertantly pushed into 9.4 instead of master, so reverting
> Revert "[PPP-4789] Updated Vulnerable Component: commons-text"

- pom.xml
for karaf ssh service (and presumably anything else in karaf reliant on them).  Standardizing on the jdk15to18 packages since these still work on JDK1.8 (they are not multiversion jars).
> [BACKLOG-37531] Bouncycastle release/version mismatch causing problems

- pom.xml
This PR to upgrade the kafka client jar to latest and requesting to merge it before as pdi-plugins-ee build is getting failed where parent pom still pointing to old kafka client(0.10.2.2) jar, so parent pom should be merged to make the build successful
> [BACKLOG-36830] - Kafka Enhancements (Plug-in Release)

- pom.xml
While not on the original code for [PPP-4751](https://jira.pentaho.com/browse/PPP-4751), this commons-lang3 version property is necessary for it!
As this property was not yet introduced on 9.3 code line (was introduced on master with [maven-parent-poms#435](https://github.com/pentaho/maven-parent-poms/pull/435), but [PDI-18433](https://jira.pentaho.com/browse/PDI-18433) was not selected to backport).
@bcostahitachivantara @renato-s @andreramos89 
[PPP-4751]: https://hv-eng.atlassian.net/browse/PPP-4751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PDI-18433]: https://hv-eng.atlassian.net/browse/PDI-18433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6440] Add commons-lang3 version property

- pentaho-ce-parent-pom/pentaho-ce-jar-parent-pom/pentaho-ce-bundle-parent-pom/pom.xml
- pom.xml
Switch to a "require.js" fork that updated the parser used by "r.js" to enable builds with modern javascript syntax
Kept the old `requirejs.version` property, because multiple projects depend on it and also because require.js version didn't change, only the libs shipped with it were updated.
@pentaho/millenniumfalcon @dcleao @pentaho/sp-branch-write please review
> chore: Enable javascript builds with ES2015+ syntax [BACKLOG-39952]

- pom.xml
Jacoco 0.8.1 does not work well with Java 11+
@cardosov @renato-s @andreramos89
> [FIX] Upgrade jacoco-maven-plugin as in BACKLOG-36442

- pom.xml
Java 8.  GWT updated to 2.10.0 for JDK17 support; was not compiling successfully under 2.9.0.
> [BACKLOG-39584] Updates for JDK17.  Build target updated to Java 11 from

- pom.xml
because it is pulling java.* dependencies into bundles and our version of karaf can't work with that.
> [BACKLOG-40255] Need to back off on the maven-bundle-plugin version

- pom.xml
This checkstyle version bump is related to the PR https://github.com/pentaho/pentaho-coding-standards/pull/44, which brings a new version for the Pentaho checkstyle standards.
> feat: bump checkstyle version

- pom.xml
Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

- pom.xml
Jira: https://hv-eng.atlassian.net/browse/PPP-4899
- Update Apache Felix HTTP Bridge version to latest minor version, containing commons-io 2.15.0, which is 2.7+, addressing CVE-2021-29425
Related PRs:
https://github.com/pentaho/pentaho-kettle/pull/9525
https://github.com/pentaho/pentaho-reporting/pull/1678
> [PPP-4899] Vulnerable Component: commons-io

- pom.xml
- adding property 'snakeyaml.version' and dependency 'org.yaml:snakeyaml:2.2'
- leaving 'safeyaml' for legacy poms and osgi related poms
Many downstream PRs depend on this property `${snakeyaml.version}`. Waiting for wingman on those PRs to clear, before officially starting review.
> [PPP-5613] Vulnerable Component: snakeyaml - part 2 ( Non OSGi upgrade)

- pom.xml
[BACKLOG-41915] -PRD-osgi fails to start with NoCLassDefFoundError in Ubuntu and MacOS environment
[BACKLOG-41915]: https://hv-eng.atlassian.net/browse/BACKLOG-41915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41915] -PRD-osgi fails to start with NoCLassDefFoundError in Ubuntu and MacOS environment

- pom.xml
[BACKLOG-41283]-Upgrading Pentaho kettle from Java EE 9 to Jakarta EE 10
[BACKLOG-41283]: https://hv-eng.atlassian.net/browse/BACKLOG-41283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-41283]-Upgrading Pentaho kettle from Java EE 9 to Jakarta EE 10

- pom.xml
[SP-6643]-Backport of PPP-5083 - Vulnerable Component: ion java (10.2 Suite)
[SP-6643]: https://hv-eng.atlassian.net/browse/SP-6643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SP-6643]-Backport of PPP-5083 - Vulnerable Component: ion java (10.2 Suite)

- pom.xml
[BACKLOG-42810]-Upgrading jackson.jaxrs to jackson.jakarta.rs to support Jakarta functionality as part of tomcat upgradation.
[BACKLOG-42810]: https://hv-eng.atlassian.net/browse/BACKLOG-42810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42810]-Upgrading jackson.jaxrs to jackson.jakarta.rs to support Jakarta functionality as part of tomcat upgradation.

- pom.xml
[BACKLOG-42885]-Upgrading Jetty version from 11.0.14 to 12.0.15 to support Jakarta EE 10
[BACKLOG-42885]: https://hv-eng.atlassian.net/browse/BACKLOG-42885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42885]-Upgrading Jetty version from 11.0.14 to 12.0.15 to support Jakarta EE 10

- pom.xml
[BACKLOG-42955]-Upgrading jackson-module-jaxb-annotations to jackson-module-jakarta-xmlbind-annotations to support Jakarta EE
[BACKLOG-42955]: https://hv-eng.atlassian.net/browse/BACKLOG-42955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-42955]-Upgrading jackson-module-jaxb-annotations to jackson-module-jakarta-xmlbind-annotations to support Jakarta EE

- pom.xml
Actual PR: https://github.com/pentaho/maven-parent-poms/pull/664
> [SP-6749] Backport of PPP-5480 - Upgrade "pax-web" to address Vulnerable Component: Tomcat 9.0.91 (10.2 Suite)

- pom.xml
- Update Apache Felix HTTP Bridge version to latest minor version, containing commons-io 2.15.0, which is 2.7+, addressing CVE-2021-29425
(cherry picked from commit 72b81732a5af9664e850853c6eb6bbc259b19226)
> [SP-6775] Update Apache Felix HTTP Bridge

- pom.xml
[BACKLOG-43612]-Upgrading Webservices to Support Jakarta EE Migration
[BACKLOG-43612]: https://hv-eng.atlassian.net/browse/BACKLOG-43612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43612]-Upgrading Webservices to Support Jakarta EE Migration

- pom.xml
Added comments to ensure that when updating tomcat, pax-web is also updated.
Also updating our custom karaf to a version that uses the same pax-web.
> feat: bump pax-web to 8.0.31 [PPP-5627]

- pom.xml
Related PRs:
- https://github.com/pentaho/maven-parent-poms-ee/pull/103
- https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1842
- https://github.com/pentaho/pentaho-analyzer/pull/2702
- https://github.com/pentaho/pentaho-platform-plugin-geo/pull/426
- https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/604
- https://github.com/pentaho/pentaho-platform-plugin-reporting/pull/896
- https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/1137
- https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/327
- https://github.com/pentaho/pentaho-det/pull/1392
- https://github.com/pentaho/pentaho-det-ee/pull/701
> [SP-6819] Backport of PPP-5516 - Vulnerable Component: requirejs 2.3.6 (10.2 Suite)

- pom.xml
[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

- pom.xml
I've previously used httpclient5:5.4.1 and httpcore5:5.3.3 as they were the versions that VFS2:2.10.0 used. As httpclient5:5.4.1 has a vulnerability, this PR is to bump both versions to the most recent ones (5.4.4 and 5.3.4, respectively).
> feat[PPP-5649]: use the most recent versions of httpclient5 and httpcore5

- pom.xml
[BACKLOG-45016]-Upgrading Tomcat from 10.1.39 to 10.1.43
[BACKLOG-45016]: https://hv-eng.atlassian.net/browse/BACKLOG-45016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-45016]-Upgrading Tomcat from 10.1.39 to 10.1.43

- .gitignore
- pom.xml
This pull request updates dependency versions related to Apache Commons FileUpload in the `pom.xml`. These changes are required, as stated in PPP-5769, to address CVE-2025-48976.
Also added `.vscode` to `.gitignore`, to ignore VS Code configuration files. **Merge this commit separately.**
Dependency version updates:
* Updated `commons-fileupload.version` from `2.0.0-M2` to `2.0.0-M4` to use a more recent milestone release.
* Updated `commons-fileupload-osgi.version` from `1.5` to `1.6.0` for the OSGi-compatible version.
* Updated `pentaho.custom.karaf.version` from `4.4.6-2025.07.01` to `4.4.6-2025.08.05`.
Dependency management improvements:
* Added a new dependency management entry with `commons-fileupload`, using the `${commons-fileupload-osgi.version}` property.
> build[PPP-5769]: Update commons-fileupload version to 2.0.0-M4 and commons-fileupload-osgi to 1.6.0

- pom.xml
[BACKLOG-45596]-Upgrade JDK properties from 11 to 17
[BACKLOG-45596]: https://hv-eng.atlassian.net/browse/BACKLOG-45596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BACKLOG-45596]-Upgrade JDK properties from 11 to 17

- pom.xml
This pull request updates the GWT (Google Web Toolkit) dependencies in the `pom.xml` file to use the latest versions and switches from the legacy `com.google.gwt` group to the newer `org.gwtproject` group. It also streamlines the GWT version management by removing a separate version property for `gwt-servlet-jakarta` and updating related comments for clarity.
**GWT Dependency Updates:**
* Updated the `gwt.version` property to `2.12.2` and added a new property for `gwt-maven-plugin.version`, ensuring all GWT dependencies use the latest compatible versions.
* Changed all GWT dependencies from the `com.google.gwt` group to the `org.gwtproject` group, since versions post-2.10.0 are only available on that groupId.
**Version Management Improvements:**
* Removed the separate …
> build[PPP-5751]: update GWT version to 2.12.2 and adjust groupId for GWT dependencies

- pom.xml
This pull request adds support for Apache SSHD libraries to the project by introducing new dependencies and a version property in the `pom.xml` file. These changes set up the project to use SSH, SFTP, and SCP features, likely for secure file transfer or remote command execution.
Dependency management updates:
* Added a new property `apache-sshd.version` (set to 2.16.0) to manage the version of Apache SSHD dependencies.
* Added the following dependencies under dependency management:
* `org.apache.sshd:sshd-core`
* `org.apache.sshd:sshd-sftp`
* `org.apache.sshd:sshd-scp`
All use the new `${apache-sshd.version}` property for versioning.
> build[PDI-20311]: add apache-sshd dependencies and version property
